### PR TITLE
Fixed, Ufixed datatypes.

### PR DESCRIPTION
**Pull request by r8d8**

### CODE REVIEW

**Comment by splix** [comment]
@r8d8 you've added `ubuntu-xenial-16.04-cloudimg-console.log` file. I guess it's not needed here, can you please remove it (with an additional commit)?

**Comment by dulanov** [comment]
@r8d8 Remove please also 'configure-parity.sh' and exclude 'out' folder from git.

**Comment by dulanov** [comment]
@r8d8 Add 'getMinValue' & 'getMaxValue' methods to 'DecimalType' class.

**Comment by splix** [comment]
@r8d8 thanks! if @dulanov approves PR, I suggest to use _Squash & Merge_ for that PR

**Pull request merged**
